# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - releases/*
  tags:
    include:
    - v*

pool:
  vmImage: 'vs2017-win2016'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run build
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    displayName: 'Build staging assets'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/build'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: GithubRelease@0
    displayName: 'Create GitHub Release'      
    inputs:
      gitHubConnection: thewahome-github-connection
      repositoryName: thewahome/react-basics
      tagSource: manual
      tag: $(Build.BuildNumber)      
      assets: |
        $(Build.ArtifactStagingDirectory)/**

  # - task: CopyFiles@2
  #   inputs:
  #     contents: '_buildOutput/**'
  #     targetFolder: $(Build.ArtifactStagingDirectory)
  
  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     pathToPublish: $(Build.ArtifactStagingDirectory)
  #     artifactName: MyBuildOutputs

  # - task: CopyFiles@2
  #   displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  #   inputs:
  #     SourceFolder: '$(System.DefaultWorkingDirectory)/build'
  #     TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # - task: PublishBuildArtifacts@1
  #   displayName: 'Publish Artifact: drop'

  # - task: GithubRelease@0
  #   displayName: 'Attach Linux x64 artifacts to GitHub Release'
  #   condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  #   inputs:
  #     gitHubConnection: thewahome-github-connection
  #     repositoryName: Thewahome/react-basics
  #     assets: '$(Build.ArtifactStagingDirectory)/react-basics.tar.gz'
  #     action: edit
  #     target: '$(Build.SourceVersion)'
  #     tag: '$(githubTag)'
  #     addChangeLog: false
  #     assetUploadMode: replace

  # - task: GithubRelease@0
  #   displayName: 'Attach Win x64 artifacts to GitHub Release'
  #   condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  #   inputs:
  #     gitHubConnection: thewahome-github-connection
  #     repositoryName: Thewahome/react-basics
  #     assets: $(Build.ArtifactStagingDirectory)/react-basics.zip
  #     action: edit
  #     target: '$(Build.SourceVersion)'
  #     tag: $(githubTag)
  #     addChangeLog: true
  #     assetUploadMode: replace
