# Node.js with webpack

# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - master
    - release/*
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest' 

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "Hello World"

  - script: |
      npmVersionString=$(npm view reactbasics version) 
      echo ##vso##vso[build.updatebuildnumber]$npmVersionString
    displayName: 'set buildnumber'

  - script: |
      npm run build
    displayName: 'build artifacts'

  - task: CopyFiles@2
    displayName: 'copy files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/build'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.ArtifactStagingDirectory)'
