name: English File transfer

on:
  push:
    branches:
      - master
    paths:
      - 'src/messages/GE.json'

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes English file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source_file: 'src/messages/GE.json'
        destination_repo: 'thewahome/building-react-apps'
        destination_folder: 'ge-content'
        destination_branch: 'master'
        user_email: ${{ secrets.ACTION_EMAIL }}
        user_name: ${{ secrets.ACTION_USERNAME }}
        commit_message: 'English file transfer'