name: Message Sender

on:
  push:
    branches:
      - 'master'
# on:
#   release:
#     types: [published]

jobs:
  send_message_job:
    #if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Send a message to Microsoft Teams
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Send a message to Microsoft Teams
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.WEBHOOK_URL}}
          title: Message ${{ github.event.release.tag_name }}
          summary: Message Summary ($RELEASE_VERSION)
          text: Message Text
          theme_color: blue
          sections: '[{ "activityTitle": "hello world" }]'
          actions: '[{ "@type": "OpenUri", "name": "lorem ipsum", "targets": [{ "os": "default", "uri": "https://localhost" }] }]'